name: Trigger auto deployment for ministry-widows-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ministry-widows-container-app-AutoDeployTrigger-8a63d21d-44e6-4d40-94cb-20aabe7b492b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MINISTRYWIDOWSCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MINISTRYWIDOWSCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MINISTRYWIDOWSCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: widowscontainers.azurecr.io
          registryUsername: ${{ secrets.MINISTRYWIDOWSCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MINISTRYWIDOWSCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: ministry-widows-container-app
          resourceGroup: ministry-widows-rg
          imageToBuild: widowscontainers.azurecr.io/ministry-widows-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


